sudo: required
services:
  - docker

before_install: 
  - docker build -t omare23/medapp -f ./desktop-client/Dockerfile.dev ./desktop-client 

script: 
  - docker run omare23/medapp npm test -- --coverage

after_success: 
  - docker build -t omare23/med-desktop-client ./desktop-client
  - docker build -t omare23/med-nginx ./nginx
  - docker build -t omare23/med-stock-management-service ./stock-management-service
#Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Then once logged in push those images to the docker hub 
  - docker push omare23/med-desktop-client 
  - docker push omare23/med-nginx
  - docker push omare23/med-stock-management-service
