version: '3'
services:
  nginx:
    restart: always
    build: 
      dockerfile: 'Dockerfile.dev'
      context: './nginx'
    ports: 
      - '80:80'  
    depends_on:
      - stock-management-service
      - desktop-client
  postgres: 
    image: 'postgres:13'  
    env_file:
      - .env.psql-service
  desktop-client:
    build: 
      context: './desktop-client'
      dockerfile: 'Dockerfile.dev'
    ports: 
      - "5173:5173"
    volumes:
      - /desktop-client/node_modules
      - ./desktop-client:/desktop-client
  stock-management-service:
      build:
        context: './stock-management-service'
        dockerfile: "Dockerfile.dev"
      ports:
        - "5000:5000"
      env_file:
        - .env.stock-management-service
      depends_on:
        - postgres
      volumes:
        - /stock-management-service/node_modules
        - ./stock-management-service:/stock-management-service

