version: '3'
services:
  postgres: 
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=

  desktop-client:
    build: 
      context: './desktop-client'
      dockerfile: 'Dockerfile.dev'
    ports: 
      - "5173:5173"

  stock-management-service: 
    build: 
      context: './stock-management-service'
      dockerfile: "Dockerfile.dev"
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=your_db_name
      - POSTGRES_USER=your_db_user 