version: '3'
services:
  nginx:
    restart: always
    build: 
      dockerfile: 'Dockerfile.dev'
      context: './nginx'
    ports: 
      - '3050:80'  
    depends_on:
      - stock-management-service
      - desktop-client
      - postgres 
  postgres: 
    image: 'postgres:13'  
    env_file:
      - .env.psql-service

  desktop-client:
    build: 
      context: './desktop-client'
      dockerfile: 'Dockerfile'
    volumes:
      - /desktop-client/node_modules
      - ./desktop-client:/desktop-client

  stock-management-service:
    build:
      context: './stock-management-service'
      dockerfile: "Dockerfile.dev"
    env_file:
      - .env.stock-management-service
    depends_on:
      - postgres
    volumes:
      - /stock-management-service/node_modules
      - ./stock-management-service:/stock-management-service

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    env_file:
      - .env.pgadmin-service
    ports:
      - "5050:5050"
    depends_on:
      - postgres  

# Kill all containers
# docker stop $(docker ps -q)

# run docker-compose on quite mode
# docker-compose up --quiet-pull -d

#Listen in on active ports:
# netstat -anvp tcp | awk 'NR<3 || /LISTEN/'
