FROM node:alpine  

WORKDIR '/desktop-client'

COPY ./package.json ./
RUN npm install 
COPY . . 
EXPOSE 5173
CMD ["npm", "run", "dev"]

#Production stage 
# FROM nginx:alpine 
# COPY --from=builder /desktop-client/dist /usr/share/nginx/html

# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]