FROM nginx

#basically saying take your ./default.conf file and override the default conf file in nginx 
#this is because our file has custom config for the reverse proxy
COPY ./default.conf /etc/nginx/conf.d/default.conf