name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Build and test Docker images
      #   run: |
      #     docker build -t omare23/medapp -f ./desktop-client/Dockerfile.dev ./desktop-client
      #     docker run omare23/medapp npm test -- --coverage

      - name: Build Docker images
        run: |
          docker build -t omare23/med-desktop-client ./desktop-client
          docker build -t omare23/med-nginx ./nginx
          docker build -t omare23/med-stock-management-service ./stock-management-service

      - name: Login to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_ID: ${{ secrets.DOCKER_ID }}

      - name: Push Docker images to Docker Hub
        run: |
          docker push omare23/med-desktop-client 
          docker push omare23/med-nginx
          docker push omare23/med-stock-management-service

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: Omare04/Medivac-Software-System@main
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Aom-medapp
          environment_name: Aom-medapp-env
          existing_bucket_name: elasticbeanstalk-us-east-2-226477727124
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
